//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 20000 Leagues Under the Sea
        ///3AM in Shibuya
        ///3am Latte
        ///8 Bit Eggplant
        ///A Dime a Dozen
        ///A State of Mint
        ///Abyssal Waters
        ///Acapulco Dive
        ///Acid
        ///Acid Green
        ///Acorn
        ///Active Volcano
        ///Agent Orange
        ///Airborne
        ///Alarm
        ///Alien Abduction
        ///Alley Cat
        ///Alligator
        ///Almond
        ///Aloe Vera
        ///Alone in the Dark
        ///Alpaca
        ///Alpine Expedition
        ///Aluminium
        ///Always Green Grass
        ///Amaretto
        ///Amaretto Sour
        ///Amazon
        ///Amber
        ///Ambrosia
        ///Amor
        ///Amore
        ///Anarchist
        ///Anchovy
        ///Ancient Scroll
        ///Angel Wing
        ///Anger
        ///Angry Pasta
        ///Another One Bites the Dust
        ///Anthracite [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string colorsList {
            get {
                return ResourceManager.GetString("colorsList", resourceCulture);
            }
        }
    }
}
